import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import WalletProviderWrapper from "./WalletProviderWrapper";
import IgnitusLogo from "./IgnitusLogo";
import { WalletMultiButton } from '@solana/wallet-adapter-react-ui';
import CurrentYear from "./CurrentYear";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-[#1a1333] to-[#232946] min-h-screen text-white font-sans">
        <WalletProviderWrapper>
          <main className="max-w-5xl mx-auto px-4 py-8">
            {children}
          </main>
          <footer className="text-center py-6 text-sm text-[#b0b3c6] border-t border-[#2d2a4a] bg-[#1a1333]/80 backdrop-blur-lg">
            © <CurrentYear /> Ignitus Networks. All rights reserved.
          </footer>
        </WalletProviderWrapper>
      </body>
    </html>
  );
}
